[package]
name = "malware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.50"
rsa = "0.9.2"
num-bigint = "0.4.3"
rand = "0.8.5"